"""Application-layer contracts (repository pattern).

Services depend on these protocols, not on SQLModel sessions, so every
service can be exercised with fakes. ``app.infrastructure.repositories``
provides the SQLite implementations bound via FastAPI dependency injection.
"""

from __future__ import annotations

from datetime import date, datetime
from typing import Protocol

from app.domain.entities import (
    ActivityLog,
    DayPlan,
    Epic,
    KnowledgeChecklist,
    Milestone,
    Note,
    Project,
    ReadingItem,
    Task,
    TaskDependency,
    UserPrefs,
    WorkSession,
)
from app.domain.enums import ActivityKind, TaskStatus


class TaskRepositoryProtocol(Protocol):
    def get(self, task_id: str) -> Task | None: ...
    def list(
        self,
        *,
        project_id: str | None = None,
        statuses: list[TaskStatus] | None = None,
        parent_id: str | None = None,
        include_archived: bool = False,
    ) -> list[Task]: ...
    def list_all_open(self) -> list[Task]: ...
    def subtasks_of(self, task_id: str) -> list[Task]: ...
    def add(self, task: Task) -> Task: ...
    def save(self, task: Task) -> Task: ...
    def delete(self, task: Task) -> None: ...
    def completed_samples(self, task_type: str, limit: int) -> list[tuple[int, int]]: ...
    def completed_between(self, start: datetime, end: datetime) -> list[Task]: ...
    def max_sequence(self, status: TaskStatus) -> float: ...


class DependencyRepositoryProtocol(Protocol):
    def list_all(self) -> list[TaskDependency]: ...
    def for_task(self, task_id: str) -> list[TaskDependency]: ...
    def add(self, dependency: TaskDependency) -> TaskDependency: ...
    def remove(self, task_id: str, depends_on_id: str) -> bool: ...


class ChecklistRepositoryProtocol(Protocol):
    def for_task(self, task_id: str) -> KnowledgeChecklist | None: ...
    def add(self, checklist: KnowledgeChecklist) -> KnowledgeChecklist: ...
    def save(self, checklist: KnowledgeChecklist) -> KnowledgeChecklist: ...


class WorkSessionRepositoryProtocol(Protocol):
    def for_task(self, task_id: str) -> list[WorkSession]: ...
    def add(self, session: WorkSession) -> WorkSession: ...
    def between(self, start: date, end: date) -> list[WorkSession]: ...
    def minutes_by_day(self, start: date, end: date) -> dict[date, int]: ...


class ProjectRepositoryProtocol(Protocol):
    def get(self, project_id: str) -> Project | None: ...
    def list(self, include_archived: bool = False) -> list[Project]: ...
    def add(self, project: Project) -> Project: ...
    def save(self, project: Project) -> Project: ...
    def delete(self, project: Project) -> None: ...
    def milestones(self, project_id: str) -> list[Milestone]: ...
    def add_milestone(self, milestone: Milestone) -> Milestone: ...
    def get_milestone(self, milestone_id: str) -> Milestone | None: ...
    def save_milestone(self, milestone: Milestone) -> Milestone: ...
    def delete_milestone(self, milestone: Milestone) -> None: ...
    def epics(self, project_id: str) -> list[Epic]: ...
    def get_epic(self, epic_id: str) -> Epic | None: ...
    def add_epic(self, epic: Epic) -> Epic: ...
    def delete_epic(self, epic: Epic) -> None: ...


class NoteRepositoryProtocol(Protocol):
    def get(self, note_id: str) -> Note | None: ...
    def list(
        self,
        *,
        kind: str | None = None,
        task_id: str | None = None,
        project_id: str | None = None,
        tag: str | None = None,
    ) -> list[Note]: ...
    def by_source_path(self, source_path: str) -> Note | None: ...
    def add(self, note: Note) -> Note: ...
    def save(self, note: Note) -> Note: ...
    def delete(self, note: Note) -> None: ...


class ReadingRepositoryProtocol(Protocol):
    def get(self, item_id: str) -> ReadingItem | None: ...
    def list(self, *, status: str | None = None, project_id: str | None = None) -> list[ReadingItem]: ...
    def due_reviews(self, on_or_before: date) -> list[ReadingItem]: ...
    def add(self, item: ReadingItem) -> ReadingItem: ...
    def save(self, item: ReadingItem) -> ReadingItem: ...
    def delete(self, item: ReadingItem) -> None: ...


class PlanRepositoryProtocol(Protocol):
    def for_date(self, plan_date: date) -> DayPlan | None: ...
    def add(self, plan: DayPlan) -> DayPlan: ...
    def save(self, plan: DayPlan) -> DayPlan: ...
    def delete(self, plan: DayPlan) -> None: ...
    def get_entry(self, entry_id: str) -> "object | None": ...
    def planned_minutes_for(self, plan_date: date) -> int: ...


class PrefsRepositoryProtocol(Protocol):
    def get(self) -> UserPrefs: ...
    def save(self, prefs: UserPrefs) -> UserPrefs: ...


class ActivityRepositoryProtocol(Protocol):
    def log(
        self,
        kind: ActivityKind,
        *,
        task_id: str | None = None,
        project_id: str | None = None,
        payload: dict | None = None,
    ) -> ActivityLog: ...
    def between(self, start: datetime, end: datetime) -> list[ActivityLog]: ...
